# Generated by Django 2.0.13 on 2021-01-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20, null=True)),
                ('context', models.CharField(max_length=20, null=True)),
                ('expect', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('time', models.IntegerField(default=0)),
                ('problem', models.CharField(max_length=20, null=True)),
                ('result', models.IntegerField(default=0)),
                ('solution', models.CharField(max_length=20, null=True)),
                ('team', models.CharField(max_length=20, null=True)),
                ('level', models.CharField(max_length=20, null=True)),
                ('department', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True)),
                ('context', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departmentgoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=20, null=True)),
                ('title', models.CharField(max_length=20, null=True)),
                ('context', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personalgoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=20, null=True)),
                ('title', models.CharField(max_length=20, null=True)),
                ('context', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
