# Generated by Django 2.0.13 on 2021-01-27 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0002_auto_20210127_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='userID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='auths', to=settings.AUTH_USER_MODEL),
        ),
    ]
