# Generated by Django 2.0.13 on 2021-01-27 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_board_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='userID',
            new_name='user',
        ),
    ]
