# Generated by Django 2.0.13 on 2021-01-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20210127_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='date',
        ),
        migrations.AddField(
            model_name='board',
            name='enddate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='startdate',
            field=models.DateField(null=True),
        ),
    ]
