# Generated by Django 2.0.13 on 2021-01-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20210129_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='expect',
            field=models.FloatField(default=0),
        ),
    ]
