# Generated by Django 2.0.13 on 2021-02-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20210129_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalgoal',
            name='departmentgoal',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
