# Generated by Django 2.0.13 on 2021-02-01 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_personalgoal_departmentgoal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalgoal',
            old_name='departmentgoal',
            new_name='department',
        ),
    ]
