# Generated by Django 2.0.13 on 2021-02-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_auto_20210201_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='task',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='uum',
            field=models.IntegerField(default=0),
        ),
    ]
