# Generated by Django 2.0.13 on 2021-02-01 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_auto_20210201_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='uum',
            new_name='num',
        ),
    ]
