# Generated by Django 2.0.13 on 2021-02-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_auto_20210201_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='context',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='departmentgoal',
            name='context',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personalgoal',
            name='context',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
