# Generated by Django 2.0.13 on 2021-02-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_auto_20210201_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='context',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
