# Generated by Django 2.0.13 on 2021-02-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_auto_20210203_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='problem',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
